
version: '2'
services:
  jenkins-server:
      container_name: "jenkins-server"
      build: .
      image: jenkins-server:latest
      environment:
        - DOCKER_SOCKET=/var/run/docker.sock
        - DOCKER_GROUP=docker
        - JENKINS_USER=jenkins
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - /var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker